services:
  web:
    build:
      context: . # Build from my_pos_system directory
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app # Mount project to /app in container
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery:
    build:
      context: . # my_pos_system
    command: celery -A my_pos_system.celery worker --loglevel=INFO # Celery worker
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery-beat:
    build:
      context: . # my_pos_system
    command: celery -A my_pos_system beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --loglevel=INFO # Celery beat
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:latest
    ports:
      - "6379:6379"