# Generated by Django 5.1.4 on 2024-12-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EAN', models.CharField(max_length=13)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('image', models.FileField(upload_to='')),
                ('available_qty', models.IntegerField()),
            ],
        ),
    ]
