# Generated by Django 5.1.4 on 2025-01-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0004_product_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
        migrations.AlterField(
            model_name='product',
            name='EAN',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
