# Generated by Django 5.1.4 on 2025-01-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0006_alter_product_discounted_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dept',
            field=models.CharField(choices=[('nonfood', 'Non-Food'), ('fruit', 'Fruit'), ('veg', 'Vegetables and Salad'), ('bakery', 'Baked Goods'), ('misc', 'Miscellaneous Items')], default='nonfood', max_length=20),
        ),
    ]
