# Generated by Django 5.1.4 on 2025-01-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0007_product_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dept',
            field=models.CharField(choices=[('grocery', 'Grocery'), ('nonfood', 'Non-Food'), ('fruit', 'Fruit'), ('veg', 'Vegetables and Salad'), ('bakery', 'Baked Goods'), ('misc', 'Miscellaneous Items')], default='grocery', max_length=20),
        ),
    ]
