# Generated by Django 5.1.4 on 2025-02-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0008_alter_product_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('trans_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('trans_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('receipt', models.ImageField(upload_to='receipts/')),
            ],
        ),
    ]
