# Generated by Django 5.1.4 on 2025-02-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_images'),
        ),
    ]
