# Generated by Django 5.1.4 on 2025-02-27 15:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0011_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_sales_reset',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_today',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
